global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'master1'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['master1:8090']
  - job_name: 'master2'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['master2:8090']
  - job_name: 'master3'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['master3:8090']
  - job_name: 'master4'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['master4:8090']
  - job_name: 'master5'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['master5:8090']
  - job_name: 'master6'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['master6:8090']

  - job_name: 'storage01'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage01:8090']
  - job_name: 'storage02'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage02:8090']
  - job_name: 'storage03'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage03:8090']
  - job_name: 'storage04'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage04:8090']
  - job_name: 'storage05'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage05:8090']
  - job_name: 'storage06'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage06:8090']
  - job_name: 'storage07'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage07:8090']
  - job_name: 'storage08'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage08:8090']
  - job_name: 'storage09'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage09:8090']
  - job_name: 'storage10'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storage10:8090']
