{
 "title": "InnerRing runtime",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node", "query": "go_goroutines" },
   { "name": "quantile", "query": "go_gc_duration_seconds" }
  ]
 },
 "panels": [
  {
   "title": "gRPC connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(neofs_grpc_connections{job=~\"^master.*$\", state=~\".*\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"^master.*$\"}",
     "legendFormat": "{{job}} goroutines"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(neofs_grpc_connections{job=~\"^master.*$\"}) by (job)",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_innerring_events_num{job=~\"^master.*$\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GoGc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\", job=~\"^master.*$\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=~\"^master.*$\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Allocs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"^master.*$\"}",
     "legendFormat": "{{job}} mem"
    }
   ]
  }
 ]
}