{
 "title": "NEOFS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chunk",
    "label": "chunk",
    "query": "neofs_objectmanager_chunk_location"
   },
   { "name": "job", "label": "Node", "query": "neofs_dataaudit_results" },
   { "name": "sgid", "label": "SG ID", "query": "neofs_dataaudit_results" },
   { "name": "number", "label": "Audit Number", "query": "neofs_dataaudit_results" }
  ]
 },
 "panels": [
  {
   "title": "#SG Passed Validation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(neofs_dataaudit_results{job=~\"$job\",sgid=~\"$sgid\",result=\"1\",number=~\"$number\"})"
    }
   ]
  },
  {
   "title": "#SG Failed Validation",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(neofs_dataaudit_results{job=~\"$job\",sgid=~\"$sgid\",result=\"0\",number=~\"$number\"})"
    }
   ]
  },
  {
   "title": "#Containers Accepted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(neofs_innerring_container_accepted{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "#Containers Awaiting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(neofs_innerring_container_awaiting{job=~\".*\"})"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
   "valueName": "total",
   "targets": [
    {
     "expr": "neofs_count_objects_on_node{job=~\"^holder.*$\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "description": "Amount of chunks stored on node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_count_objects_on_node{job=~\"^holder.*$\"}",
     "legendFormat": "{{job}} stored objects"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "neofs_innerring_events_num{job=~\"^master.*$\"}",
     "legendFormat": "{{job}} processed events"
    }
   ]
  },
  {
   "title": "gRPC connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(neofs_grpc_connections{job=~\"^holder.*$\", state=~\"^.*$\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"^holder.*$\"}",
     "legendFormat": "{{job}} goroutines"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(neofs_grpc_connections{job=~\"^holder.*$\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Allocs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"^holder.*$\"}",
     "legendFormat": "{{job}} mem"
    }
   ]
  }
 ]
}