version: '2.4'
services:

  cli:
    image: nspccdev/neofs-cli:${NEOFS_IMAGES_VERSION}
    command: ["bash"]
    container_name: neofs-cli
    depends_on:
      - storage10
    volumes:
      - ../data:/data
      - ./keys/user.key:/user.key:ro
    environment:
      - NEOFS_CLI_KEY=/user.key
      - NEOFS_CLI_ADDRESS=storage10:8080
