version: '2.4'

services:
  minio:
    image: nspccdev/neofs-s3:${NEOFS_S3GATE_VERSION}
    container_name: minio-gw-backend
    depends_on:
      storage01:
        condition: service_healthy
    environment:
      MINIO_ACCESS_KEY: AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y
      MINIO_SECRET_KEY: KxDgvEKzgSBPPfuVfw67oPQBSjidEiqTHURKSDL1R7yGaGYAeYnr
    ports:
      - "9001:9000"
    command: gateway neofs storage01:8080
