version: '2.4'

services:
  drop-nginx:
    image: nginx:latest
    container_name: neofs-drop-nginx
    depends_on:
      - drop-ui
      - drop-backend
    volumes:
      - ./nginx/nginx-drop.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 7001:80

  drop-ui:
    image: nspccdev/neofs-drop-ui:${NEOFS_DROPUI_VERSION}
    container_name: neofs-drop-ui

  drop-backend:
    image: nspccdev/neofs-dropin:${NEOFS_DROP_VERSION}
    container_name: neofs-drop-backend
    depends_on:
      storage01:
        condition: service_healthy
    volumes:
      - ./keys/user.key:/user.key:ro
    environment:
      - DROP_KEY=user.key
      - DROP_LISTEN_ADDRESS=:8080
      - DROP_AUTO_CREATE_CID=true
      - DROP_NEOFS_ADDRESS=neofs-storage-01:8080
