# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus

    # <string, required> datasource type. Required
    type: prometheus

    # <bool> mark as default datasource. Max one per org
    isDefault: true

    # <string, required> access mode. direct or proxy. Required
    access: proxy

    # <int> org id. will default to orgId 1 if not specified
    orgId: 1

    # <string> url
    url: http://prometheus:9090

    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true

    # <map> fields that will be converted to json and stored in jsonData
    jsonData:
      # Lowest interval/step value that should be used for this data source
      timeInterval: 5s
